ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
TARGET = check
ARDUINO_LIBS = Serial Servo
BOARD_TAG = mega2560 # also uno and others from boards.txt

ARDUINO_PORT = /dev/cu.usb*

include Arduino.mk
